format_version: 2
pipelines:
  vue-gotham-todo:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/serifreedom/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ./gotham-todo/build.sh
                    arguments:
                      - .
                - exec:
                    command: ./gotham-todo/apply-infrastructure.sh
                - exec:
                    command: ./gotham-todo/copy-static-files.sh    
